// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQK68GTmhn-P_yWv7F7967YhfGme3aiA',
    appId: '1:524858853482:web:59e62c69883ed05a68e213',
    messagingSenderId: '524858853482',
    projectId: 'shop-flow-571d7',
    authDomain: 'shop-flow-571d7.firebaseapp.com',
    storageBucket: 'shop-flow-571d7.firebasestorage.app',
    measurementId: 'G-37C0H6ZFWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq293EfPqi1d8HWKwrRuhRGFn3ApZmqKg',
    appId: '1:524858853482:android:cf13287499e7ad0968e213',
    messagingSenderId: '524858853482',
    projectId: 'shop-flow-571d7',
    storageBucket: 'shop-flow-571d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv0rnIktr_k8Z2hVHN599O2OWamxlIQGc',
    appId: '1:524858853482:ios:f522ee0b7a5680b568e213',
    messagingSenderId: '524858853482',
    projectId: 'shop-flow-571d7',
    storageBucket: 'shop-flow-571d7.firebasestorage.app',
    iosClientId:
        '524858853482-54f6ilhe6ss64oro5j92r9iq436jbckf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv0rnIktr_k8Z2hVHN599O2OWamxlIQGc',
    appId: '1:524858853482:ios:f522ee0b7a5680b568e213',
    messagingSenderId: '524858853482',
    projectId: 'shop-flow-571d7',
    storageBucket: 'shop-flow-571d7.firebasestorage.app',
    iosClientId:
        '524858853482-54f6ilhe6ss64oro5j92r9iq436jbckf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaQK68GTmhn-P_yWv7F7967YhfGme3aiA',
    appId: '1:524858853482:web:5adcfc7d93c0c24868e213',
    messagingSenderId: '524858853482',
    projectId: 'shop-flow-571d7',
    authDomain: 'shop-flow-571d7.firebaseapp.com',
    storageBucket: 'shop-flow-571d7.firebasestorage.app',
    measurementId: 'G-KGT61G83D3',
  );
}
